version: "3.8"

services:

  dotnet-sdk:
    build:
      context: ./app # see ./app/Dockerfile
    ports:
      - 8080:8080
    volumes:
      - type: bind
        source: ./app
        target: /source/app
    secrets:
      - ms-sql-db-password
    environment:
      - IS_DOCKER=TRUE
    # depends_on:
    #    ms-sql-db:
    #      condition: service_healthy
    
  ms-sql-db:
    image: mcr.microsoft.com/mssql/server:2022-CU9-ubuntu-20.04
    deploy:
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 120s
    secrets:
      - ms-sql-db-password
    # if you want to store DB file and log in host - 
    # put them into /var/opt/mssql-mount
    volumes:
      - type: volume
        source: ms-sql-db-data
        target: /var/opt/mssql
      - type: bind
        source: ./infrastructure/ms-sql-db/mount
        target: /var/opt/mssql-mount
    environment:
      - ACCEPT_EULA=Y
      - MSSQL_SA_PASSWORD_FILE=/run/secrets/ms-sql-db-password 
    ## switch from ports to expose if you don't need to access DB from hosting machine
    #expose:
    #  - 1433
    ports:
      - 1433:1433
    healthcheck:
      test: /opt/mssql-tools/bin/sqlcmd -S localhost -U sa -P $(cat /run/secrets/ms-sql-db-password) -Q "SELECT 1" -b -o /dev/null
      interval: 10s
      timeout: 3s
      retries: 10
      start_period: 10s

  mongo:
    image: mongo
    deploy:
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 120s
    secrets:
      - mongo-password
    # if you want to store DB in host - 
    # switch /data/db volumes (mongo does not let you choose specific location per db)
    volumes:
      - type: volume
        source: mongo-data
        target: /data/db
      # - type: bind
      #   source: ./infrastructure/mongo/mount
      #   target: /data/db
      - type: volume
        source: mongo-config
        target: /data/configdb

    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD_FILE=/run/secrets/mongo-password
    ports:
      - 27017:27017
    healthcheck:
      test: ["CMD","mongosh", "--eval", "db.adminCommand('ping')"]
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 10s

  # mongodb web admin tool
  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    secrets:
      - mongo-password
    environment:
      - ME_CONFIG_BASICAUTH_USERNAME=root
      - ME_CONFIG_BASICAUTH_PASSWORD_FILE=/run/secrets/mongo-password
      - ME_CONFIG_MONGODB_ENABLE_ADMIN=true
      - ME_CONFIG_MONGODB_ADMINUSERNAME=root
      - ME_CONFIG_MONGODB_ADMINPASSWORD_FILE=/run/secrets/mongo-password
      - ME_CONFIG_MONGODB_SERVER=mongo
      - ME_CONFIG_MONGODB_PORT=27017
      
## we wil mount folder instead 
volumes:
  ms-sql-db-data:
  mongo-data:
  mongo-config:
secrets:
  ms-sql-db-password:
    file: infrastructure/ms-sql-db/password.txt
  mongo-password:
    file: infrastructure/mongo/password.txt

