version: "3.8"

services:
  dotnet-sdk:
    build:
      context: ./app
    ports:
      - 8080:8080
    volumes:
      - type: bind
        source: ./app
        target: /source/app
    depends_on:
       db:
         condition: service_healthy
    

#The `db-password` secret is used
# to set the database password. You must create `db/password.txt` and add
# a password of your choosing to it before running `docker compose up`.
  db:
    image: mcr.microsoft.com/mssql/server:2022-CU9-ubuntu-20.04
    deploy:
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 120s
    secrets:
      - db-password
    # DB files will be stored in ./db/data directory
    volumes:
      - type: volume
        source: db-data
        target: /var/opt/mssql
      - type: bind
        source: ./db/mount
        target: /var/opt/mssql-mount
    environment:
      - ACCEPT_EULA=Y
      - MSSQL_SA_PASSWORD=TTTTtt444444%%%%
      #- MSSQL_SA_PASSWORD_FILE=/run/secrets/db-password
      
    ## switch from ports to expose if you don't need to expose port to hosting machine network
    #expose:
    #  - 1433
    ports:
      - 1433:1433

    healthcheck:
      test: /opt/mssql-tools/bin/sqlcmd -S localhost -U sa -P "TTTTtt444444%%%%" -Q "SELECT 1" -b -o /dev/null
      interval: 10s
      timeout: 3s
      retries: 10
      start_period: 10s
      
## we wil mount folder instead 
volumes:
  db-data:
secrets:
  db-password:
    file: db/password.txt

